#!/usr/bin/env python
import gzip
import sys

import click

from lxml import etree
from lxml.etree import tostring as etree2string
from simplejson import dumps as jdumps
from xmltodict import parse as x2dparse

@click.group()
def discogs():
    pass


@discogs.command()
@click.option("-o", "--outfile", type=click.File('w'),
              default=sys.stdout)
@click.argument("in_files", nargs=-1, type=click.File('r'))
def artists(outfile, in_files):
    for i_file, in_file in enumerate(in_files, 1):
        click.echo("{}".format(in_file.name))
        in_fname = getattr(in_file, 'name', 'Unknown')
        if in_fname.endswith('.gz'):
            res = process_xml(gzip.GzipFile(fileobj=in_file))
        else:
            res = process_xml(in_file)
            
        click.echo("File {}, {}: processed {} artist records".format(
            i_file, in_fname, res))

def process_xml(in_file):
    context = etree.iterparse(in_file, events=('end',), tag='artist')

    for i, (event, el) in enumerate(context, 1):
        res = jdumps(x2dparse(etree2string(el)))
        el.clear()
        while el.getprevious() is not None:
            del el.getparent()[0]

    del context
    return i
    
def process_fname(in_fname):
    with open(in_fname, 'r') as in_file:
        process_xml(in_file)
            
if __name__ == '__main__':
    discogs()
    
